[package]
name = "ebpfguard-common"
version = "0.1.0"
edition = "2021"

[features]
default = []
user = ["aya"]

[dependencies]
aya = { version = ">=0.11", optional = true }

[lib]
path = "src/lib.rs"
