[workspace]
resolver = "2"

members = [
    "ebpfguard",
    "ebpfguard-common",
    "xtask",
    "examples/*",
]
exclude = ["ebpfguard-ebpf", "tests"]


[patch.crates-io]
aya = { git = "https://github.com/deepfence/aya-rs", branch = "btf-fixes" }
